### ISSUE TITLE
I cannot open the ball instance section

### ISSUE THREAD

**Issue by Blaze1XM** [laggron42/BallsDex-DiscordBot#44]
I use Microsoft Edge and i turn on the bot, i try to enter the ball instance section and then appears this:
{"detail":"Can't found field 'count' in model <class 'ballsdex.core.models.BallInstance'>"}

**Comment by Blaze1XM** [comment]
![image](https://user-images.githubusercontent.com/102857291/224121171-d36a7e0d-35dc-4fae-8bf0-eb1a5e3726a9.png)

**Comment by laggron42** [comment]
This might be the very first issue reporting an actual bug and not asking about the `.env` file, congratulations 🎉 

Sounds like I didn't change something since dropping the `count` field in caught countryballs. Btw I'm curious, did you see that error message in your internet browser directly? It just shows error 500 for me 🤔

**Comment by Blaze1XM** [comment]
I think they appear in different ways depending on the web browser, in Edge you enter one and it appears like this.

And also thanks El Laggron for trying to help me with this.

**Comment by Blaze1XM** [comment]
Now works, thank you El Laggron
